// use this file to keep all of the configurations for passport 

// Heroku muse use the Node and npm version installed on local machine: declare the node and npm version in package.json (use node -v and npm -v to find current version)

const passport = require('passport');
// require('dotenv').config;
const session = require('express-session');

// Google OAuth20 has various properties.  We only need Strategy for this app.
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/keys');

// access user model class
const User = mongoose.model('users');

// first use the user model argument, then done argument
passport.serializeUser((user, done) => {
    // user.id is the id assigned by MongoDB to the user.  This is different than the profile id, which is specific to Google/LinkedIn/etc. that they may use to sign in
    // cannot assume everyone will have a GoogleId, but we can assume they will have an ID generated by MongoDB
    // OAuth is used to sign in user.  After that, we use our own internal ID, user.id. 
    done(null, user.id);
});

// instruct passport to handle authentication specific to Google strategy - users can use this to authenticate themselves inside the application
// create new instance of GoogleStrategy, pass in configuration to instruct how to authenticate users inside application
// console.developers.google.com
passport.use(
    // GoogleStrategy has an internal identifier called "google" - use this in passport authentication

    new GoogleStrategy(
        {
            // format below does not work.  Try importing variables
            clientID: keys.googleClientID,
            clientSecret: keys.googleClientSecret,
            // give Passport the below route to send users after they grant access to application
            // You must use the full URL here, or you will get an error
            callbackURL: '/auth/google/callback'
        }, 
            // the below callback function includes the "done" callback tells passport that the query is complete and it does not need to find or create a user, so it can resume authentication process
            (accessToken, refreshToken, profile, done) => {
                // console.log('access token', accessToken);
                // access token expires after a certain amount of time.  Refresh token automatically updates access token.
                // console.log('refresh token', refreshToken);
                // console.log('profile: ', profile)

                // any time we reach out to MongoDB database in any way, it is asynchronous.  Must use a "promise" (tool in JS that handles asyncrhonous code)

                // Initiate a search over all the records in the collection.
                // Look through User's collection, find the first record inside collection with a googleId of profileId (existingUser will be one instance, or existingUser will be null)
                User.findOne({ googleId: profile.id }).then(existingUser => {
                    // first argument if user has googleId of profileId
                    if(existingUser) {
                        // have record with a given profileId
                        // "done" needs two callbacks - 1) an err object, which communicates with passport if something is wrong, 2) the result of the callback - existingUser
                        done(null, existingUser);
                    } else {
                        // we don't have record with a given profileId, so make a new record
                        // create a new user model instance "User" (Uppercase) with a googleId of profile.id
                        new User({ googleId: profile.id })
                        // to get the model instance to persist to MongoDB, add ".save();" at end
                        .save()
                        // second argument user, who was just saved
                        // we make use of this second user below inside of the promise callback, since we may have made additional changes since the original User
                        // save the instance above, then in the callback below, we get another model instance of "user" (lowercase)
                        .then(user => done(null, user));
                    }
                });
            }
    )
);